"use client";

import { useState } from "react";

export function JobActions({ jobId, status }: { jobId: string; status: string }) {
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState<"cv" | "cover" | "interview">("cv");
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [provider, setProvider] = useState("mock");
  const [error, setError] = useState("");

  async function run(action: "cv" | "cover" | "interview") {
    setBusy(true);
    setError("");
    setTab(action);
    setResult(null);
    try {
      let r: Response;
      if (action === "cv") r = await fetch("/api/cvs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ jobId }) });
      else r = await fetch(`/api/ai/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ jobId }) });
      const data = await r.json();
      if (!r.ok) throw new Error(data.error || "Failed");
      setResult(data);
      setProvider(data.provider || "mock");
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <>
      <button onClick={() => setOpen(true)} className="text-sm text-brand-600 font-medium hover:underline">AI Prep</button>

      {open && (
        <div className="fixed inset-0 z-50 bg-ink-900/40 backdrop-blur-sm flex items-center justify-center p-4" onClick={() => setOpen(false)}>
          <div className="bg-white rounded-2xl shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 sticky top-0 bg-white">
              <h2 className="font-bold text-ink-900">AI Preparation</h2>
              <button onClick={() => setOpen(false)} className="text-slate-400 hover:text-slate-600 text-xl">×</button>
            </div>

            <div className="flex gap-2 px-6 pt-4">
              {[
                { k: "cv" as const, l: "Tailor CV" },
                { k: "cover" as const, l: "Cover letter" },
                { k: "interview" as const, l: "Interview prep" },
              ].map((t) => (
                <button key={t.k} onClick={() => run(t.k)} disabled={busy}
                  className={`px-3 py-1.5 rounded-lg text-sm font-medium border transition-colors ${tab === t.k && result ? "bg-brand-600 text-white border-brand-600" : "bg-white border-slate-200 text-slate-600 hover:border-brand-300"}`}>
                  {t.l}
                </button>
              ))}
            </div>
            <div className="px-6 py-2 flex items-center gap-2 text-[11px] text-slate-400">
              <span className={`inline-flex h-2 w-2 rounded-full ${provider === "mock" ? "bg-amber" : "bg-mint"}`} />
              generated by <span className="font-semibold uppercase">{provider}</span> provider
            </div>

            <div className="px-6 pb-6">
              {busy && <p className="text-sm text-slate-400 animate-pulse">Generating…</p>}
              {error && <p className="text-sm text-rose-600">{error}</p>}

              {result && tab === "cv" && (
                <div>
                  <div className="mb-4 flex items-center gap-3 flex-wrap">
                    <span className="inline-flex px-2.5 py-1 rounded-lg bg-brand-50 text-brand-700 text-xs font-semibold">{result.matchScore}% match</span>
                    <span className="text-xs text-slate-400">{result.reused ? "Reused best library CV" : "Generated new tailored version"}</span>
                    <a className="btn-primary !px-3 !py-1.5 !text-xs" href={`/api/cvs/${result.cv.id}/docx`}>Download .docx</a>
                  </div>
                  <div className="rounded-xl bg-slate-50 p-4">
                    <p className="text-sm text-slate-700"><b>Summary:</b> {result.cv.content.summary}</p>
                    <p className="text-sm text-slate-700 mt-2"><b>Skills:</b> {result.cv.content.skills.join(", ")}</p>
                    <p className="text-xs text-slate-400 mt-2">Truthfulness guardrail: generated from your master CV only — no invented facts.</p>
                  </div>
                </div>
              )}

              {result && tab === "cover" && (
                <pre className="whitespace-pre-wrap text-sm text-slate-700 font-sans bg-slate-50 rounded-xl p-4">{result.text}</pre>
              )}

              {result && tab === "interview" && (
                <div className="space-y-3">
                  {result.questions.map((q: any, i: number) => (
                    <div key={i} className="rounded-xl bg-slate-50 p-4">
                      <span className="inline-flex px-2 py-0.5 rounded-md bg-brand-50 text-brand-700 text-[11px] font-semibold uppercase mb-1">{q.kind}</span>
                      <p className="text-sm font-medium text-ink-900">{q.question}</p>
                      {q.sampleAnswer && <p className="text-xs text-slate-400 mt-1">{q.sampleAnswer}</p>}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}
